# Generated by Django 2.2.2 on 2019-06-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('identity', models.SmallIntegerField(choices=[(1, '管理员'), (2, '求职者'), (3, '老板')])),
            ],
        ),
    ]
