# Generated by Django 2.2.2 on 2019-06-13 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=300, null=True, verbose_name='简历')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positionName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Provide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ManyToManyField(to='core.Candidate')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Position')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='identity',
        ),
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.CharField(default='nmsl', max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='userrole',
            field=models.SmallIntegerField(choices=[(1, '管理员'), (2, '应聘者'), (3, '公司')], default=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='匿名', max_length=32, verbose_name='真实姓名'),
        ),
        migrations.CreateModel(
            name='Select',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, '通过'), (2, '未通过'), (3, '待审核')], default=3)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Candidate')),
                ('provide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Provide')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='position',
            field=models.ManyToManyField(through='core.Provide', to='core.Position'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
    ]
