# Generated by Django 2.2.2 on 2019-06-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190613_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(default='北京', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.SmallIntegerField(choices=[(1, '500人以下'), (2, '1000人以下'), (3, '2000人以下'), (4, '5000人以下'), (5, '10000人以下'), (6, '10000人以上')], default=6, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '互联网'), (2, '机械制造'), (3, '交通'), (4, '石油化工'), (5, '通讯')], default=1, null=True),
        ),
    ]
