# Generated by Django 2.2.2 on 2019-06-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_company_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='head',
            field=models.FileField(default='/static/images/default.jpeg', upload_to=''),
        ),
    ]
