# Generated by Django 2.2.2 on 2019-06-14 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='birthday',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='candidate',
            name='email',
            field=models.CharField(default='123@qq.com', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='finishEdu',
            field=models.DateField(default=datetime.date(2012, 2, 2), null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], default=1),
        ),
        migrations.AddField(
            model_name='candidate',
            name='tel',
            field=models.CharField(default='11111111111', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='bio',
            field=models.CharField(max_length=1024, null=True, verbose_name='简历'),
        ),
    ]
