# Generated by Django 2.2.2 on 2019-06-15 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190614_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='size',
            field=models.SmallIntegerField(choices=[(1, '1-99人'), (2, '100人以上'), (3, '500人以上'), (4, '1000人以上'), (5, '5000人以上'), (6, '10000人以上')], default=6, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '互联网'), (2, '电子商务'), (3, '广告营销'), (4, '生活服务'), (5, '金融证券')], default=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='select',
            unique_together={('provide', 'candidate')},
        ),
    ]
